name: Package Builder

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build package
        run: bash scripts/build.sh ${{ inputs.package_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package_name }}
          path: /output/
