name: AUR Launcher

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        package: [quickshell-git]
      max-parallel: 1
    uses: ./.github/workflows/builder.yml
    with:
      package_name: ${{ matrix.package }}
